server {
    listen 5500;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(js|css)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri =404;
    }

    location / {
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri $uri/ /index.html;
    }
}
